---
- name: Generate autoupdate.sh script
  template:
    src: "mycroft-core/bin/autoupdate.sh.j2"
    dest: "{{ _mycroft_core_directory }}/bin/autoupdate.sh"
    owner: "{{ mycroft_user }}"
    group: "{{ mycroft_user }}"
    mode: 0755

- name: Create systemd mycroft-autoupdate.service file
  template:
    src: "etc/systemd/system/mycroft-autoupdate.service.j2"
    dest: "/etc/systemd/system/mycroft-autoupdate.service"
  notify:
    - daemon-reload

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Enable Mycroft AI autoupdate service
  systemd:
    name: mycroft-autoupdate
    enabled: yes
