---
- name: Raspberry Pi OS detection
  stat:
    path: /etc/rpi-issue
  register: detect

- name: Ensure tsched=0 is set for module-udev-detect
  lineinfile:
    path: /home/{{ prepi_pi_user }}/.config/pulse/default.pa
    regexp: "^load-module module-udev-detect"
    line: "load-module module-udev-detect tsched=0"
    create: yes
    mode: 0644
  register: config_tsched

- name: Pulseaudio default configuration
  blockinfile:
    path: "/home/{{ mycroft_user }}/.config/pulse/default.pa"
    block: |
      # Mycroft optimization
      unload-module module-suspend-on-idle

      .ifexists module-role-ducking.so
      load-module module-role-ducking
      .endif

      .ifexists module-echo-cancel.so
      load-module module-echo-cancel aec_method=webrtc
      .endif
  register: config_modules

- name: Pulseaudio daemon configuration
  blockinfile:
    path: "/home/{{ mycroft_user }}/.config/pulse/daemon.conf"
    block: |
      # Mycroft optimization
      # Check bug https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1060
      enable-shm = no

      resample-method = ffmpeg
      default-sample-format = s24le
      default-sample-rate = 48000
      alternate-sample-rate = 44100
    create: yes
    mode: 0644
  register: config_daemon

# A handler should be use in this case but for some reasons
# there is a bug with the systemd module and the scope not
# keep as user.
- name: Restart PulseAudio if configuration changed
  systemd:
    name: pulseaudio
    scope: user
    state: restarted
  notify:
    - restart-mycroft-audio
    - restart-mycroft-voice
  when: config_tsched.changed or config_modules.changed or config_daemon.changed

- name: Create Mycroft configuration
  template:
    src: "mycroft-core/mycroft.conf.j2"
    dest: "{{ _mycroft_home }}/.mycroft/mycroft.conf"
    mode: 0644
  notify: apply-mycroft-configuration

- name: Block specific IP
  iptables:
    chain: INPUT
    destination_port: "'{{ _mycroft_bus_port }}'"
    protocol: tcp
    jump: DROP
    comment: "Drop connections on Mycroft message bus service"
  when: mycroft_bus_firewall is defined and mycroft_bus_firewall | bool
  become: yes
