---
- name: Retrieve service facts
  service_facts:

- name: Set mycroft_audio_status fact
  vars:
    service_name: "mycroft-audio.service"
  set_fact:
    mycroft_audio_status: "{{ ansible_facts.services[service_name]['state'] }}"
  when: ansible_facts.services[service_name] is defined

- name: Set mycroft_voice_status fact
  vars:
    service_name: "mycroft-voice.service"
  set_fact:
    mycroft_voice_status: "{{ ansible_facts.services[service_name]['state'] }}"
  when: ansible_facts.services[service_name] is defined

- name: Install required packages
  package:
    name: "{{ _mycroft_packages }}"

- name: Create {{ _mycroft_ramdisk_directory }} mountpoint
  file:
    path: "{{ _mycroft_ramdisk_directory }}"
    state: directory
    owner: "{{ mycroft_user }}"
    group: "{{ mycroft_user }}"
    mode: 0755

- name: Mount {{ _mycroft_ramdisk_directory }} as tmpfs
  mount:
    path: "{{ _mycroft_ramdisk_directory }}"
    src: tmpfs
    fstype: tmpfs
    opts: "defaults,noatime,nodiratime,nosuid,nodev,noexec,size=512M"
    state: mounted
