---
- name: Create systemd services
  template:
    src: "etc/systemd/system/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0644
  loop: "{{ _mycroft_services }}"
  notify:
    - daemon-reload
    - restart-mycroft

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Start Mycroft AI services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ _mycroft_services }}"
