---
- name: Remove Mycroft configuration from PulseAudio default
  blockinfile:
    path: "/home/{{ mycroft_user }}/.config/pulse/default.pa"
    block: |
      # Mycroft optimization
      unload-module module-suspend-on-idle
      load-module module-role-ducking
    state: absent
  register: config_modules

- name: Remove Mycroft configuration from PulseAudio daemon
  blockinfile:
    path: "/home/{{ mycroft_user }}/.config/pulse/daemon.conf"
    block: |
      # Mycroft optimization
      resample-method = ffmpeg
      default-sample-format = s24le
      default-sample-rate = 48000
      alternate-sample-rate = 44100
    state: absent
  register: config_demon

# A handler should be use in this case but for some reasons
# there is a bug with the systemd module and the scope not
# keep as user.
- name: Restart PulseAudio if configuration changed
  systemd:
    name: pulseaudio
    scope: user
    state: restarted
  when:
    - config_modules.changed
    - config_daemon.changed

- name: Check if mycroft-bus systemd unit file exists
  stat:
    path: /etc/systemd/system/mycroft-bus.service
  register: unit

- name: Stop Mycroft services
  systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ _mycroft_services }}"
  when: unit.stat.exists

- name: Remove Mycroft directories and files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ _mycroft_core_directory }}"
    - "{{ _mycroft_skills_directory }}"
    - "/opt/mycroft"
    - "{{ _mycroft_home }}/.mycroft"
    - "{{ _mycroft_home }}/.config/mycroft"
    - /ramdisk/mycroft
    - /tmp/mycroft
    - /tmp/mycroft.json
    - "{{ _mycroft_home }}/.mycroft_cli.conf"
    - "{{ _mycroft_home }}/.profile_mycroft"
    - "{{ _mycroft_home }}/.asoundrc"
    - /var/tmp/mycroft_web_cache.json
    - /tmp/mycroft-msm.lck
    - /tmp/msm_lock
    - /tmp/identity-lock

- name: Remove Mycroft commands from PATH
  blockinfile:
    path: "{{ _mycroft_home }}/.profile"
    block: |
      # include Mycroft commands
      source ~/.profile_mycroft
    state: absent

- name: Remove systemd unit files
  file:
    path: "/etc/systemd/system/{{ item }}.service"
    state: absent
  loop: "{{ _mycroft_services }}"

- name: Uninstall packages
  package:
    name: "{{ _mycroft_packages }}"
    state: absent

- name: Purge pip cache
  shell:
    cmd: |
      pip cache purge || true
    executable: /bin/bash
    warn: no
  changed_when: no

- name: Packages cleaning
  shell:
    cmd: |
      apt-get autoremove -y
      apt-get autoclean -y
      apt-get clean
      sync
    executable: /bin/bash
    warn: no
  changed_when: no
