---
- name: daemon-reload
  systemd:
    daemon-reload: true

- name: restart-mycroft
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ _mycroft_services }}"

- name: restart-mycroft-skills
  systemd:
    name: mycroft-skills
    state: restarted

- name: restart-pulseaudio
  systemd:
    name: pulseaudio
    state: restarted

- name: apply-mycroft-configuration
  shell:
    cmd: |
      source venv-activate.sh
      python -m mycroft.messagebus.send "configuration.updated" "{}"
    chdir: "{{ _mycroft_core_directory }}"
    executable: /bin/bash
