---
- name: daemon-reload
  systemd:
    daemon-reload: yes

- name: restart-mycroft
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop: "{{ _mycroft_services }}"

- name: restart-mycroft-skills
  systemd:
    name: mycroft-skills
    state: restarted

- name: apply-mycroft-configuration
  shell:
    cmd: |
      source venv-activate.sh
      python -m mycroft.messagebus.send "configuration.updated" "{}"
    chdir: "{{ _mycroft_core_directory }}"
    executable: /bin/bash

- name: restart-mycroft-audio
  systemd:
    name: mycroft-audio
    state: restarted
  when: mycroft_audio_status is defined and mycroft_audio_status == "running"

- name: restart-mycroft-voice
  systemd:
    name: mycroft-voice
    state: restarted
  when: mycroft_voice_status is defined and mycroft_voice_status == "running"
